# Site settings
title: Le Blog de Tarik Peudon-Bellalou, Co-Fondateur de Clicboutic
email: tarik.peudon@clicboutic.com
description: > # this means to ignore newlines until "baseurl:"
  Tarik est un entrepreneur nomade. Il écrit des articles sur le design, l’expérience client, et le développement d’une entreprise en SaaS. 
permalink: /:title/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
